name: app_products
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.1

dependencies:
  appsize: ^1.2.1
  bloc: ^8.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  go_router_flow: ^6.0.0+3
  intl: ^0.17.0
  products_client:
    path: packages/products_client
  products_ui:
    path: packages/products_ui
  very_good_cli: ^0.12.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/img/
